// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0wwfTil9FgFB3mgze1P96OBrH3_CRes',
    appId: '1:89072288699:web:b6c9ee705c5e7309527a9e',
    messagingSenderId: '89072288699',
    projectId: 'authtutorial-ab8fe',
    authDomain: 'authtutorial-ab8fe.firebaseapp.com',
    databaseURL: 'https://authtutorial-ab8fe-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-ab8fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2uUmj3_UyIW15sMeErpcEZAhO0Kq6XA',
    appId: '1:89072288699:android:628388cdd240c554527a9e',
    messagingSenderId: '89072288699',
    projectId: 'authtutorial-ab8fe',
    databaseURL: 'https://authtutorial-ab8fe-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-ab8fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIlfS8k9fngvo8MFwWP5IS9jt7fM28QsM',
    appId: '1:89072288699:ios:1dd2a42f7851721d527a9e',
    messagingSenderId: '89072288699',
    projectId: 'authtutorial-ab8fe',
    databaseURL: 'https://authtutorial-ab8fe-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-ab8fe.appspot.com',
    iosClientId: '89072288699-k35lehov4d00erh3d9t6g54odph11i7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIlfS8k9fngvo8MFwWP5IS9jt7fM28QsM',
    appId: '1:89072288699:ios:1dd2a42f7851721d527a9e',
    messagingSenderId: '89072288699',
    projectId: 'authtutorial-ab8fe',
    databaseURL: 'https://authtutorial-ab8fe-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-ab8fe.appspot.com',
    iosClientId: '89072288699-k35lehov4d00erh3d9t6g54odph11i7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );
}
